openapi: 3.1.0
info:
  title: Scrabble API
  description: This document describes an API for playing scrabble. It can be
    used and consumed by any client, so feel free to provide one in a new module
    here.
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /games:
    summary: List resource for scrabble games
    description: Create new games and browse all games
  /games/{gameId}:
    summary: Interaction with a single game
    description: Interaction with a single game



